### ISSUE TITLE
Error selecting COverlap toolset in Fiji

### ISSUE THREAD

**Issue by jkh1** [mambroset/COverlap-a-Fiji-co-localization-toolset#1]
After following installation instructions [here](https://github.com/mambroset/COverlap-a-Fiji-co-localization-toolset?tab=readme-ov-file#installation), the following error is produced at step 6 (selecting the COverlap toolset):
![image](https://github.com/mambroset/COverlap-a-Fiji-co-localization-toolset/assets/5235745/6f7196a2-aac6-4fe4-bc63-647face05961)
This is with Fiji 2.14.0/1.54i, Java 1.8.0_172 on Ubuntu 20.04

**Comment by mambroset** [comment]
You have downloaded the html link instead of actually downloading the .ijm file. I have modified the link so it goes directly to the raw .ijm file. Let me know if it fixed it :)

**Comment by jkh1** [comment]
Didn't see that one 🤦 . Fixed. Thanks.
